Feature competition in agriculture
Mikhail-Kh/android-project pull request #4
Opened 2020-09-29 11:32 UTC by Mikhail-Kh

![S00929-140510](https://user-images.githubusercontent.com/61590423/94553059-94b5f200-0260-11eb-90e4-d0974bc62ed8.jpg)

2020-09-29 14:25 UTC, TMSlebedev requested changes

2020-09-29 14:25 UTC, TMSlebedev commented on app/src/main/java/by/khryshchanovich/androidapplication/Main6Activity.kt
> +                        delay(1000)
Хорошо бы вынести общую логику, раз она повторяется

2020-09-29 14:25 UTC, TMSlebedev commented on app/src/main/java/by/khryshchanovich/androidapplication/Main5Activity.kt
> +class Main5Activity : AppCompatActivity() {
А где ViewModel?

2020-09-30 17:13 UTC, Mikhail-Kh commented on app/src/main/java/by/khryshchanovich/androidapplication/Main6Activity.kt
> +                        delay(1000)
Доделываю

2020-09-30 17:13 UTC, Mikhail-Kh commented on app/src/main/java/by/khryshchanovich/androidapplication/Main5Activity.kt
> +class Main5Activity : AppCompatActivity() {
Доделаю

2020-10-01 19:34 UTC, TMSlebedev reviewed
Не забудь запросить ревью у коллег, когда доделаешь эту дз

2020-10-02 13:26 UTC, Mikhail-Kh commented
![S01002-162025](https://user-images.githubusercontent.com/61590423/94928164-ef06bb00-04cb-11eb-9a8a-1a479e4c17db.jpg)
![S01002-162040](https://user-images.githubusercontent.com/61590423/94928183-f5953280-04cb-11eb-8a70-94bec431bedf.jpg)

2020-10-02 15:52 UTC, stasenkots requested changes

2020-10-02 15:52 UTC, stasenkots commented on app/src/main/java/by/khryshchanovich/androidapplication/CompetitionViewModel.kt
> +class CompetitionViewModel : ViewModel() {
Too many reapeated logic

2020-10-02 15:52 UTC, stasenkots commented on app/src/main/java/by/khryshchanovich/androidapplication/Main6Activity.kt
> +        competitionViewModel.counter1.observe(this, Observer { newCounter1 ->
names "counter" "new counter"  hard to understand

2020-10-19 20:03 UTC, merged